kind: Pod
apiVersion: v1
metadata:
  name: environment-test
spec:
  containers:
  - name: nginx
    image: nginx
    environment:
    - name: course
      value: 'kubernetes'
    - name: duration
      value: '20hours'
