apiVersion: v1
kind: Service
metadata:
  name: nginx
spec: 
  selector:
    name: frontend
    project: expense
    component: frontene
    environment: dev
  ports:
  - protocols: TCP
    port: 80 # service-port
    targetPort: 80 # target-port